default[:zookeeper][:home] = '/opt/zookeeper/current'
default[:zookeeper][:id] = '1'
default[:zookeeper][:client_port] = '2182'
default[:zookeeper][:mode] = 'standalone'
default[:zookeeper][:data_dir] = '/opt/zookeeper/current/data'
default[:zookeeper][:client][:discovery_mechanism] = "blackboard" # other valid values is "adstore"
default[:zookeeper][:members] = []
default[:zookeeper][:quorum] = 1
default[:zookeeper][:ready] = false
set[:cvolume][:fs_type] = 'xfs'
